version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - kafka-network

#  kafka-producer:
#    image: kafka-producer:latest
#    container_name: kafka-producer
#    ports:
#      - "9200:9200"
#    depends_on:
#      - kafka
#    networks:
#      - kafka-network

#  kafka-consumer:
#    image: kafka-consumer:latest
#    container_name: kafka-consumer
#    ports:
#      - "9201:9201"
#    depends_on:
#      - kafka
#    networks:
#      - kafka-network

networks:
  kafka-network:
    driver: bridge
